### ISSUE TITLE
re-define fails to transform AMD module to CommonJS format during build if module starts with semicolon.

### ISSUE THREAD

**Issue by wizardzloy** [damianbaar/re-define#6]
```javascript
;define([
    'd3'
  , 'moment'
  ]
, function (d3, moment) {})
```
This code is failing to be transformed to the CommonJS format during re-define build. This causes runtime error afterwards. Same code without semicolon before ```define``` works just fine

**Comment by damianbaar** [comment]
good spot, thanks :+1:
